language: C
compiler: gcc
before_install: sudo apt-get update
install: sudo apt-get install swig python-dev openjdk-7-jdk openjdk-7-jre-headless golang-go gccgo ruby-dev
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "c4jV4KRTF3YrML+To9pntpZH9fODEJ3KYAMFruzic5hYGKLVqLFtiM6dNqUgXQKSqbo+zPrCDcZ/Prh1JCslzNgVIiS3P0GaTNYk9F3gS3YQwLvWWmyLvjGfGuYRbxsc22gG1ASFLsxRVmO4kzFY+kdmHFwlUGVtyn1dVJXJ3wY="
  matrix:
    - CONF="--enable-openssl-install"
    - CONF="--enable-openssl-install --enable-python"
    - CONF="--enable-openssl-install --enable-java"
    - CONF="--enable-openssl-install --enable-ruby"
    - CONF="--enable-openssl-install --enable-go" GCCGOFLAGS="-static-libgcc" SWIGGOPARAMS=" "

script: autoreconf -vsi && ./configure $CONF && make && make check

addons:
  coverity_scan:
    project:
      name: "frankmorgner/openpace"
      description: "Cryptographic library for EAC version 2"
    notification_email: oepen@informatik.hu-berlin.de
    build_command_prepend: autoreconf -vsi && ./configure --enable-openssl-install
    build_command: make
    branch_pattern: coverity_scan
